### ISSUE TITLE
Rifle recipe gives Uzi as result

### ISSUE THREAD

**Issue by ghost** [JSJBDEV/ArmsOfFire#4]
Check the recipe config for the Rifle, it will produce the Uzi

**Comment by JSJBDEV** [comment]
ive changed it in github but cannot build it right now so I shall leave this open, sorry its late, I havent really had time or energy to mod recently

**Comment by ghost** [comment]
> ive changed it in github but cannot build it right now so I shall leave this open, sorry its late, I havent really had time or energy to mod recently

not a problem man, i'll close the issue
